import localFont from "next/font/local";
import "./normalize.css";
import "./globals.css";
import { logout } from "./_actions/auth";
import Header from '@/app/_components/header/header'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <form action={logout}>
          <button className="bg-gray-400 p-2"> Logout</button>
        </form>
        {children} 
      </body>
    </html>
  );
}
